version: '2'

services: 
  nginx:
    image: nginx:alpine
    container_name: 'nginx-port81'
    tty: true
    volumes:
        - ./www:/www
        - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 81:80
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"
  
  